### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by kasinathsg**
Here is the [proof](https://www.loom.com/share/01a8479ff1fa4cfab0dabde6f5faf8c0?sid=3de11d29-4a32-4a69-83f9-3def7d835f1c) for work done

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
thanks @kasinathsg for your submission. the self-viva is covers `DDL commands` well.

however a demo is missing (you did not execute the commands shown). please consider re-submitting with the demo link.

thanks.

**Comment by kasinathsg** [comment]
Here is the demo link

https://www.loom.com/share/4eac5d4199b04bd59d5a91bc5c29a013?sid=68a49eab-d3d3-4eea-a031-993a54bebd72

**Comment by th3c0d3br34ker** [comment]
hey @kasinathsg pls re-submit on `kalvium.community` as well.

**Comment by kasinathsg** [comment]
I have re-submitted on kalvium.community

**Review by th3c0d3br34ker — APPROVED** [review]
thanks @kasinathsg, please go ahead and merge this PR.

**Pull request merged**
